[tool.poetry]
name = "avi-metadata-processor"
version = "0.1.0"
description = "A tool for processing the metadata of AVI files"
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.7"
argparse = "*"
mutagen = "*"

[tool.poetry.dev-dependencies]
